feat: add bookings
Hell-enn/java-shareit pull request #2
Opened 2024-06-06 15:41 UTC by Hell-enn

2024-06-08 20:19 UTC, z8q requested changes

2024-06-08 20:19 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> addedUserOpt = userJpaRepository.findById(userId);
Внутри метода validateUpdateUser уже есть вызов userJpaRepository.findById, можно было бы возвращать полученный результат и использовать его, чтобы не делать повторный запрос

2024-06-08 20:19 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
У нас в схеме присутствует unique constraint на поле email, который вернет ошибку и код 400 при попытке добавления дубля.
Тут мы бросаем RuntimeException, в exception handler проходим через метод handleAnyError пользователю придет код 500,
возможно стоит убрать весь блок for

2024-06-08 20:19 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> userOpt = userJpaRepository.findById(userId);
можно использовать конструкцию .findById(userId).orElseThrow(...), чтобы ниже не проверять if (userOpt.isEmpty())

2024-06-08 20:19 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingJpaRepository.findById(bookingId).get();
тут тоже можно добавить orElseThrow и использовать исключение из первого блока if – NotFoundException("Бронирование не найдено!");

2024-06-09 09:31 UTC, Hell-enn commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
Я понимаю, что извлекать всех пользователей для валидации одного поля ни в коем случае нельзя, потому что рано или поздно это станет слишком затратной операцией. Но мне пришлось пока оставить этот костыль, ибо спринг на этапе сборки почему-то не использует схему, он собирает базу на основе аннотаций (при этом почему-то unique = true в @Column также не использует). Почему так происходит, и как с этим быть, пока не поняла, но я в процессе поиска ответа на этот вопрос...

2024-06-09 09:32 UTC, Hell-enn commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
![Uploading Screenshot_6.png…]()

2024-06-09 09:32 UTC, Hell-enn commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
![Screenshot_7](https://github.com/Hell-enn/java-shareit/assets/113332510/508f1ce0-47a5-4115-8866-96208d741382)

2024-06-09 09:33 UTC, Hell-enn commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
![Screenshot_6](https://github.com/Hell-enn/java-shareit/assets/113332510/aede679a-a2e1-45f8-8407-157b1e64b7d1)

2024-06-09 19:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (user != null && user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userId)) {
Похоже ответ приходит с кодом 400 (BAD_REQUEST), а в тесте ожидается 409 (CONFLICT) или 500 (INTERNAL_SERVER_ERROR), то есть в exception-хендлере можно попробовать иначе обработать

Проблем со схемой не увидел
Когда убираю блок if, в консоли выводится ошибка
```
Unique index or primary key violation: "PUBLIC.UQ_USER_EMAIL_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'bob@yandex.ru' )";
```

2024-06-09 19:19 UTC, z8q approved these changes

2024-06-11 01:18 UTC, merged